name: WakaTime Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anuraghazra/wakatime-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          BLOCKS: "░▒▓"
          SHOW_TIME: true
          SHOW_TOTAL: true
