name: WakaTime Readme Stats

on:
  workflow_dispatch:
  schedule:
    # Berjalan setiap 12 jam
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "⣿⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀"
          CODE_LANG: "txt"
          TIME_RANGE: "last_7_days"
