# .github/workflows/update_stats.yml

name: WakaTime Stats

on:
  schedule:
    # Berjalan setiap hari pukul 17:00 UTC (00:00 WIB)
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # --- OPSI TAMPILAN ---
          SHOW_TITLE: true
          TIME_ZONE: Asia/Jakarta
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
